#pragma once

#undef ORTHOTREE_LOOPIVDEP
#ifdef CRASH_UNDEF
#undef CRASH_UNDEF
#undef CRASH
#endif // CRASH_UNDEF
#ifdef CRASH_IF_UNDEF
#undef CRASH_IF_UNDEF
#undef ORTHOTREE_CRASH_IF
#endif // CRASH_IF_UNDEF
